name: SpiderMic
board: Fysect E4

#spi:
#  miso_pin: gpio.19
#  mosi_pin: gpio.23
#  sck_pin: gpio.18

#sdcard:
#  cs_pin: gpio.5
#  card_detect_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1:
  macro2:
  macro3:

uart1:
  txd_pin: gpio.22
  rxd_pin: gpio.21
  baud: 115200
  mode: 8N1
stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0

kinematics:
  SpiderMic:
<<<<<<< HEAD
<<<<<<< HEAD
    kinematic_segment_len_mm: 0.2
    x_max_mm: 374
    y_max_mm: 374
    softLimits: false
    # limits ingnored if softLimits is false
    softLimits_mm: 200
    # limits calculated from the center
=======
    R_b_mm: 6
=======
>>>>>>> 91a7b666 (movement debugged, correct distances)
    kinematic_segment_len_mm: 1.0
    x_max_mm: 374
    y_max_mm: 374
    softLimits: false
    # limits ingnored if softLimits is false
    x_min_mm: 0
    x_max_mm: 374
    y_min_mm: 0
<<<<<<< HEAD
    y_max_mm: 370
>>>>>>> 58210624 (settings accepted, ready for final implementation)
=======
    y_max_mm: 374
>>>>>>> 91a7b666 (movement debugged, correct distances)

axes:
  shared_stepper_disable_pin: gpio.25
  homing_runs: 4
  x:
    steps_per_mm: 50
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 526
    # sqrt(pow(_max_x, 2) + pow(_max_y, 2))
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.34:high
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2
      tmc_2209:
        uart_num: 1
        addr: 1
        cs_pin: NO_PIN
        r_sense_ohms: 0.15
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 31
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        # run_mode: SpreadCycle
        homing_mode: Stallguard
        homing_amps: 0.500
        use_enable: false
        direction_pin: gpio.26
        step_pin: gpio.27:pu
        disable_pin: NO_PIN
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 650
      seek_mm_per_min: 650
      settle_ms: 1000
      seek_scaler: 1.1
      feed_scaler: 1.1
  y:
    steps_per_mm: 50
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 526
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.35:high
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2
      tmc_2209:
        uart_num: 1
        addr: 2
        cs_pin: NO_PIN
        r_sense_ohms: 0.15
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 31
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: Stallguard
        homing_amps: 0.500
        use_enable: false
        direction_pin: gpio.32
        step_pin: gpio.33:pu
        disable_pin: NO_PIN
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 650
      seek_mm_per_min: 650
      settle_ms: 1000
      seek_scaler: 1.1
      feed_scaler: 1.1
  z:
    steps_per_mm: 50
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 526
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.23:low
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2
      tmc_2209:
        uart_num: 1
        addr: 3
        cs_pin: NO_PIN
        r_sense_ohms: 0.15
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 31
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: Stallguard
        homing_amps: 0.500
        use_enable: false
        direction_pin: gpio.12
        step_pin: gpio.14:pu
        disable_pin: NO_PIN
    homing:
      cycle: 3
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 650
      seek_mm_per_min: 650
      settle_ms: 1000
      seek_scaler: 1.1
      feed_scaler: 1.1
  a:
    steps_per_mm: 50
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 526
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      tmc_2209:
        uart_num: 1
        addr: 0
        cs_pin: NO_PIN
        r_sense_ohms: 0.15
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 31
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: Stallguard
        homing_amps: 0.500
        use_enable: false
        direction_pin: gpio.17
        step_pin: gpio.16:pu
        disable_pin: NO_PIN
    homing:
      cycle: -1
      allow_single_axis: false
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 650
      seek_mm_per_min: 650
      settle_ms: 1000
      seek_scaler: 1.1
      feed_scaler: 1.1
